storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  'ima':
    access: $all
    publish: $all
  '**':
    access: $all
    publish: $all
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
